version: '3'
services:
    nginx:
        restart: always
        build: 
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '3050:80'
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app
        stdin_open: true
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - /app/node_modules
            - ./server:/app
        stdin_open: true
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: test_user
            MONGO_INITDB_ROOT_PASSWORD: test_user
        ports:
            - '27017:27017'
